# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pip-tools
        pip-compile --resolver=backtracking --output-file requirements.txt requirements.in requirements-dev.in
        pip install -r requirements.txt
    - name: Checking code quality step 1
      if: always()
      run: flake8 .
    - name: Checking code quality step 2
      if: always()
      run: pylint ./codeapp
    - name: Checking code quality step 3
      if: always()
      run: black . --check --diff
    - name: Checking code quality step 4 (type hints)
      if: always()
      run: mypy .
    - name: Checking code quality step 5 (imports)
      if: always()
      run: isort . --check-only --diff

    - name: Testing database connection
      if: always()
      run: pytest -k database_connection

    - name: Checking your model
      if: always()
      run: pytest -k models

    - name: Checking the quality of your HTML code
      if: always()
      run: pytest -k html

    - name: Check your plot image
      if: always()
      run: pytest -k image
    
    - name: Check the web services
      if: always()
      run: pytest -k webservices

    - name: Running tests and evaluating code coverage for the unitary tests
      if: always()
      run: |
        coverage run -m pytest
        coverage report -m --fail-under=100

